frontend:
     @echo Installing Frontend
catalogue:
     @echo Intsalling Catalogue
cart:
     @echo Intsalling Cart
user:
     @echo Intsalling User
shipping:
     @echo Intsalling Shipping
payment:
     @echo Intsalling Payment
mongodb:
     @echo Intsalling Mongodb
redis:
     @echo Intsalling Redis
mysql:
     @echo Intsalling MySQL
rabbitmq:
     @echo Intsalling RabbitMQ